name: 'Publish Kernel in AdaLab'
description: 'An action to publish a Docker image as a new kernel in AdaLab'
inputs:
  kernel_name:
    description: 'Name of the kernel'
    required: true
  kernel_description:
    description: 'Description of the kernel'
    required: true
  harbor_registry_url:
    description: 'AdaLab Harbor registry URL'
    required: true
  harbor_password:
    description: 'Password for the AdaLab Harbor registry'
    required: true
  harbor_robot_user:
    description: 'AdaLab Harbor registry robot user'
    required: true
  image_name:
    description: 'Name of the Docker image'
    required: true
  image_tag:
    description: 'Tag of the Docker image'
    required: true
  adalab_user_token:
    description: 'User token for AdaLab API'
    required: true
  adalab_username:
    description: 'Username for AdaLab API'
    required: true
  adalab_api_url:
    description: 'AdaLab API URL'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Log in to AdaLab Docker registry
      shell: bash
      run: |
        echo "${{ inputs.harbor_password }}" | docker login -u '${{ inputs.harbor_robot_user }}' --password-stdin "${{ inputs.harbor_registry_url }}"

    - name: Push Docker image
      shell: bash
      run: |
        docker tag ${{ inputs.image_name }}:${{ inputs.image_tag }} ${{ inputs.harbor_registry_url }}/kernels_temp/${{ inputs.image_name }}:${{ inputs.image_tag }}
        docker push ${{ inputs.harbor_registry_url }}/kernels_temp/${{ inputs.image_name }}:${{ inputs.image_tag }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install --extra-index-url https://staging-adalab.adamatics.io/devpi/admin/adalib-dev adalib

    - name: Register image as new kernel
      shell: bash
      run: |
        python <<EOF
        from adalib_auth import config
        adalib_config = config.get_config(adaboard_api_url="${{ inputs.adalab_api_url }}", token="${{ inputs.adalab_user_token }}")
        import adalib.harbor as harbor
        harbor.create_image_metadata(
            source_type="registry",
            source_repository="${{ inputs.image_name }}",
            source_tag="${{ inputs.image_tag }}",
            project_name="kernels",
            repository_name="${{ inputs.image_name }}",
            tag="${{ inputs.image_tag }}",
            type_id="kernel",
            name="${{ inputs.kernel_name }}",
            description="${{ inputs.kernel_description }}",
            username="${{ inputs.adalab_username }}",
        )
        EOF

